yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-values: disable
  key-ordering: disable
  octal-values: disable
  quoted-strings: disable
