name: Test HELLO_WRLD!

on: [push]

env:
    my_env: "Hello!"

jobs:
    get_env:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run a one-line script
              run: npm run setenv
