name: HELLO_WRLD_SECOND!

on: [push]

jobs:
    build:
        needs: Yaml Lint
        if: ${{ success() }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run a one-line script
              run: echo Hello, world!
