name: Yaml Lint

on:
  [pull_request]
  # pull_request:
  # commit-ignore:
  # - [skip ci]
  # - [ci skip]

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
